version: '2'

services:
  app:
    image: 'drychan-bot:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - PGAAS_USERNAME=${PG_USER}
      - PGAAS_PASSWORD=${PG_PWD}
      - PGAAS_URL=jdbc:postgresql://db:5432/${PG_DB}
      - TOKEN=${VK_TOKEN}
      - CONFIRMATION_CODE=${VK_CONF_CODE}
      - GROUP_ID=${VK_GROUP_ID}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
    ports:
      - "80:8080" #vk.api references only to 80 port
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  db-data: