version: '2'

services:
  app:
    image: 'drychan-bot:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - PGAAS_USERNAME=ddulaev
      - PGAAS_PASSWORD=""
      - PGAAS_URL=jdbc:postgresql://db:5432/drychanbot
      - TOKEN=c6414558667b30150ae3f4600f875d836fa12ca0866322aa7164428671798f28634bf26fa3a3f85c56e24
      - CONFIRMATION_CODE=7a4df1ea
      - GROUP_ID=81585002
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=drychanbot
      - POSTGRES_USER=ddulaev
      - POSTGRES_PASSWORD=""
    restart: on-failure